id: tweet-sentiment-extraction
name: Tweet Sentiment Extraction
problem_type: kaggle
description: converfix/problems/tweet-sentiment-extraction/description.md

grader:
  name: jaccard-similarity
  metric_lower_is_better: false
  grade_fn: converfix.problems.tweet-sentiment-extraction.grade:grade

preparer: converfix.problems.tweet-sentiment-extraction.prepare:prepare
